### ISSUE TITLE
Session Form Fix

### ISSUE THREAD

**Issue by wongshington** [wongshington/QuickStarter#1]
fix render of login errors on modal
fix toggling of logged in or logged out on incorrect form submit

**Comment by s-pangburn** [comment]
Hey Jesse! Just a note to make sure you update the Heroku link in your wiki before adding me onto issues, it makes it easier for me to review your features!

When you're ready, make sure to add "PA Review: MVP Name" as a sub-issue to each milestone and add me when you're ready for me to review each feature!
