### ISSUE TITLE
Production README

### ISSUE THREAD

**Issue by anastassia-b** [wongshington/QuickStarter#26]
Is missing! 

**Content:**
- [ ] Has a `# Title`
- [ ] Links to the Wiki design documents
- [ ] Describes technologies used
- [ ] Describes core functionality
- [ ] Lists future directions
- [ ] Fills out `Description` and `Website` at the top of the repo.

**Format:**
- [ ] Uses markdown formatting
- [ ] Includes code snippets (with triple backticks, and the language ` ```javascript...``` `)
- [ ] Includes screenshots / gifs

**Optional:**
- [ ] Describes technical challenges
- [ ] Add `topics` to the top of the repo

**Comment by wongshington** [comment]
looool I'm gonna whip one up now

**Comment by anastassia-b** [comment]
LOL
![spongebob-timecard](https://user-images.githubusercontent.com/26614978/52889075-40193e00-3133-11e9-9f4a-3247d3a45ca9.jpg)

**Comment by anastassia-b** [comment]
Why'd you close this??? You haven't gotten a review 🙄
