### ISSUE TITLE
MVP: User Auth

### ISSUE THREAD

**Issue by wongshington** [wongshington/QuickStarter#28]
- [x] Users can create and view (index and show) projects
- [x] Can upload photos, text descriptions, and levels of donations
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by wongshington** [comment]
yo jesse this is spiffy
jk this is not spiffy

**Comment by s-pangburn** [comment]
for what it's worth, i think it's pretty spiffy
